services:
  n8n:
    image: n8nio/n8n:2.3.4
    container_name: n8n-main
    restart: always
    ports:
      - '5678:5678'
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_AUTH_TOKEN=af5c543f1b8f989fd2f3500dcf399dc8860746bda8de4cf1fef1cc3981501684
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_BROKER_PORT=5679
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_RUNNERS_PYTHON_ENABLE=true
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_RUNNERS_CONFIG_PATH=/etc/n8n-task-runners.json
    command: start
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_files:/data
      - ./n8n-task-runners.json:/etc/n8n-task-runners.json

  n8n-runner-python:
    build: .
    container_name: n8n-runner-python
    restart: always
    command: python
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_AUTH_TOKEN=af5c543f1b8f989fd2f3500dcf399dc8860746bda8de4cf1fef1cc3981501684
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
      - N8N_RUNNERS_CONFIG_PATH=/etc/n8n-task-runners.json
    volumes:
      - ./n8n-task-runners.json:/etc/n8n-task-runners.json
    depends_on:
      - n8n

volumes:
  n8n_data:
    external: true